"use client";
import { useState, useEffect } from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingScreen from './components/LoadingScreen';
import Footer from './components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata est une constante, elle ne peut pas être dans un client component
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);
  const [showLoadingScreen, setShowLoadingScreen] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false); // Déclenche le fondu de la page de chargement et l'apparition du contenu
    }, 3000); // Simule un chargement de 3 secondes

    const hideTimer = setTimeout(() => {
      setShowLoadingScreen(false); // Masque complètement la page de chargement après son fondu
    }, 3500); // 3 secondes de chargement + 0.5 seconde de transition de fondu

    return () => {
      clearTimeout(timer);
      clearTimeout(hideTimer);
    };
  }, []);

  return (
    <html lang="fr" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        {showLoadingScreen && <LoadingScreen isFadingOut={!isLoading} />}
        <div className={`content-wrapper ${isLoading ? 'hidden' : 'visible'}`}>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
